data:
  raw_data_path: "data/raw/data.csv"
  cleaned_data_path: "data/processed/clean_data.csv"
  feature_data_path: "data/processed/engineered_data.csv"
  test_data_path: "data/processed/test_data.csv"

model:
  model_output_path: "models/model.pkl"
